### ISSUE TITLE
Unable to run examples

### ISSUE THREAD

**Issue by ArcyFlores** [google/boardgame.io#150]
Tried running examples and came across unexpected token error at /Users/aflores/Desktop/softDev/practice/boardgame.io/node_modules/koa-static/index.js:39
    return async function serve (ctx, next) {
                 ^^^^^^^^

**Comment by Stefan-Hanke** [comment]
The library uses babel with the 2015 preset that does not transform async functions. Looks like [Node supports async since version 7.6](https://medium.com/@eli.goldberg/async-await-is-here-node-7-6-0-9f5a9904eb41). Incidentally, that's also the [minimal version](https://github.com/google/boardgame.io/blob/master/package.json#L48) as per the package.json.

What version are you running?

**Comment by ArcyFlores** [comment]
I see, I'm running v6.11.2
