### ISSUE TITLE
ctx api,

### ISSUE THREAD

**Issue by pociej** [google/boardgame.io#186]
Hi, 
Tell me if im wrong, but from what i read for now : 
a) framework makes decision what server backed i should use 
b) ctx id read only. 
I would like to use other server in backend but client from framework. I need game to be in same state after refresh and i want to allow player to save the game in current state and back to it later, additionally i want data of saved games to be accessible on server. 
At first glance it seems to be impossible with server of my choice because of a) and b) above. 
Am i wrong?

**Comment by jstacoder** [comment]
it is entirely backend agnostic, what you are referring to, the `Server`, is a helper supplied by the framework to maintain state between clients via a websocket connection. It does not serve your app for you, although like you said, you have that taken care of, and you don’t need to use the websocket helper provided, you are always free to reimplement it. You just need to supply something with a compatible interface.

**Comment by pociej** [comment]
@jstacoder thx for your reply. Yeah i read how server is implemented and you are right. Anyways main problem i described in orginal issue description is still here. I want to be able to leave game and back to it at any point of time, but : https://github.com/google/boardgame.io/blob/master/src/core/flow.js#L619-L627 . It sees that Flow ctx is hardcoded here and there is no api to be able start game in turn 7 on player 3 move. It should be hard to do but still it has to be done. Right ?

**Comment by jstacoder** [comment]
Yes, the default Flow implementation (`FlowWithPhases`) does hardcode that, but that is because it works for 90% of use cases, although the reason the `Flow` object is abstracted from the `Game` is so that if it doesn’t work for you you can reimplement the base Flow class to allow for the flow you need, ie you can let it take the current player or turn as a parameter or w/e, but that is what you want, to create a custom Flow, just read through FlowWithPhases to see what is needed in your custom flow.

**Comment by pociej** [comment]
Yeah i see that reimplementation is not a hard piece of work. Im just surprised its not the part of default, and even more surprised that, based on your words, for 90% of use case its ok. Is there any important reason to have it implemented like it is now, or you are open for pull request. Maybe it should be separate class not reimplementation `FlowWithPhases`? Also im going to make meteor.js server for `boardgame.io` and i wonder if i should place in separate package or i could also make PR.

**Comment by nicolodavis** [comment]
@pociej This should hopefully clear a few things up:

- State that you want persisted should go to a database like Mongo: http://boardgame.io/#/multiplayer?id=database
- If you want to write a connector for another database, that is also possible by implementing [one](https://github.com/google/boardgame.io/blob/master/src/server/db.js#L63).
- The game restores state from the DB, which is why you don't need an API to move forward to turn 7, for example. The initial Flow constructor that you linked to is only relevant to a new game. After that, the client asks the server if state for this game exists. If it does, it restores the game to that state (so if you left off at turn 7 / player 3 the last time, the game will be moved forward to that automatically).
- You should not be implementing a new flow class unless you have a very very rare and peculiar case, which this is not.
- If you want to use Meteor instead of Koa, that would involve writing your own server. I would prefer that it stay in a separate package (I'm happy to link to it in the docs here).
