### ISSUE TITLE
Protect lobby API

### ISSUE THREAD

**Issue by scally** [google/boardgame.io#198]
Followup for #189 , as it stands today it's possible for anyone to call the lobby API. 

Some ideas:

1. Shared token between lobby webserver & lobby API
2. ???

**Comment by nicolodavis** [comment]
Shared token sounds good to me.

Another option would be to expose **create game** and **join game** as just normal JS functions. A lobby implementation can then just use them directly as wrappers over `db.set` to create games. The ACL's are now provided at the DB level to prevent the outside world from calling them directly.

We can still expose them through a RESTful API like #189 does, but maybe we can also refactor the POST handler logic into simple functions so that they're reusable directly as well?

**Comment by scally** [comment]
I'll start with the token idea, I'm not sure I fully understand the other option atm.

**Comment by scally** [comment]
@nicolodavis a PR is up for this at #204 . It's branched from #189, so it will require a rebase whenever #189 lands, but if you want to see the real diffs for it for now, it's in the last commit.
