### ISSUE TITLE
Translate api docs to Korean

### ISSUE THREAD

**Issue by Crepepepe** [google/boardgame.io#200]
Hello, I want to translate api docs to Korean.
Would I make folder like `docs/api/ko/*.md`?

**Comment by Crepepepe** [comment]
@nicolodavis Chrome's translate is good when just translate listed words, but pretty bad for complex sentence. Because Korean has different word order. For syncing, I will keep updating api docs.

**Comment by nicolodavis** [comment]
I did some research on how other projects handle localization. Redux, for example, has translators host the docs in separate [repositories](https://github.com/camsong/redux-in-chinese). React also does the [same](https://github.com/discountry/react), although they might be moving to a more formal process for localization soon.

I think I'd like to follow a similar model, where we can link to the Korean translation from the main docs here (rather than host it in this repo directly). It would make more sense to keep everything in the same place once we have actual localization infrastructure (and translations in multiple languages).

So, let me know once you're done translating the docs and I'll add a link to it from the main documentation. Thanks for volunteering for this!

**Comment by nicolodavis** [comment]
I'll close this for now. Please re-open it once you are done and I'll add a link to the documentation.
