### ISSUE TITLE
Demo without game logic

### ISSUE THREAD

**Issue by arakholia** [google/boardgame.io#26]
Any thoughts about creating a demo which doesn't enforce any game logic? I'm essentially imagining a playground-style app which provides non-programmers the tools to create custom assets (cards, tokens, background images for boards) to form a library for a game. The app then is only responsible for synchronizing gamestate, both public and private (as per #16), as well as a few generic actions (token placement/movement, stacking cards to form a deck, shuffling of deck, dice rolls, etc.). Clearly without enforcing game logic there is nothing to prevent cheating. The hope is to model playing board games in real life, where the players themselves are the enforcers of game logic.

**Comment by nicolodavis** [comment]
You can certainly model all the interactions with the tokens on the board as "moves".

For example:
1. Move card from deck to hand.
2. Move card from hand to board.
3. etc.

None of these do anything more than just simulate movements on the board. These movements get synchronized with other clients over the network, and no game logic is enforced because you didn't code any.

**Comment by nicolodavis** [comment]
Closing this issue. Feel free to re-open if this doesn't answer your question.
