### ISSUE TITLE
Animation broken for multiplayer chess example

### ISSUE THREAD

**Issue by Felizardo** [google/boardgame.io#84]
Animation does not work for the player who is doing the move on multiplayer chess example. See gif:
<img src="https://user-images.githubusercontent.com/1034631/35084178-8bc7d10a-fbd7-11e7-97a5-27187c69eab4.gif" width="300"/>

If I sync with commit 810f5859a28b10d9be5780138bf00975e9f67303 -- 6 days ago, it works fine.

**Comment by nicolodavis** [comment]
This is almost certainly due to https://github.com/google/boardgame.io/commit/af3a7b591759ed65d22d27ce036d9d33caaaf4f5.

The change is that the client that makes the move also receives a status update from server, so a token will see:

```
location A --> location B --> location B
```

in quick succession. We'll need to debounce the animation logic on the client side.

**Comment by nicolodavis** [comment]
Thanks, and sorry about the breakage!
