### ISSUE TITLE
Undo / Redo

### ISSUE THREAD

**Issue by nicolodavis** [google/boardgame.io#95]
Features planned:
- [x] Undo moves in the current turn.
- [x] Redo moves in the current turn.
- [x] Mark certain moves as not undo-able (to prevent peeking at a card, for example).
- [x] Reset the entire game state.
- [ ] Move Undo/Redo out of game events (make them analogous to reset #155).

**Comment by karel1980** [comment]
Other possibly related features:
Other feature ideas (inspired by online-go.com):
- forking (creating a new game based on a specific game state)
- reviewing: Commenting on moves after the fact
- analysis: Simulate moves to inspect the outcome (not very useful if there is randomness involved)
- planning conditional moves (if x happens, y in my next move - useful for slow paced, correspondence style games)

**Comment by karel1980** [comment]
Just to be clear: these are just brainstorming suggestions, not features I really want or need right now. There's no need for implementation, but maybe they are things which can be taken into account when designing the undo/redo functionality.

**Comment by sladwig** [comment]
Since most (all?) of the attributes you can add to the flow object, you can also add to the individual phases, my first attemt was to add `undo: true` to the phase where undo makes sense and so only 'applying' undo to the moves in that phase. I was a bit surprised to find out that I could only apply undo to the whole game, thus making undo not yet usable out of the box for me.

I do however like the idea of allowing undo only on specific moves, being more ganular and probably more useful for other games, where you can do undoable and not undoable moves in one phase. I don't have a specific case in mind, but guess there are games out there which do. 

My idea would be to use an array similar to 'allowedMoves' e.g. 'undoableMoves', which could be added generally to the flow object or to be more specific to each phase, allowing moves to be undoable in one phase but not in another. For some games it might even be interesting for undoableMoves to take a function like `(G, ctc) => [undoable Moves]` to decide undoable moves based on the gamestate, but not sure if this is really necessary... So what do you think?

I do have some time on my hands in the next couple of weeks, so could work on this.

**Comment by Stefan-Hanke** [comment]
I like how the current Dominion implementation handles Undo: It asks all other players for permission. If everyone is OK with the Undo, it is performed.

**Comment by sladwig** [comment]
Sounds good, definitely a good scenario to keep in mind. How I see it we shouldn't impose a specific way to undo moves though. 
At Backgammon it happens sometimes, that a player moves a stone and then sees another move makes more sense and as long as you are not finished with both moves, you are free to change the first one as you please. So the first move is undoable the second is not...
I don't really see a problem implementing both undo versions with the undoableMoves list, but maybe it makes sense to introduce a concept similar to passing, to make the asking of other players easier? For example something like a 'phase order' maybe, so you can enter an unlinear 'ask players for undo' phase, but that's just a very vague idea. 
Or maybe it makes sense to give something like an 'isUndoableIf' hook, which then marks the moves in the undo list as undoable or not. As I see it the developer would then be pretty free to implement the undo in the way of his choosing.
I will sleep over it...

**Comment by sladwig** [comment]
Ok, if nobody is up for it, I will work on the undoableMoves then.

**Comment by nicolodavis** [comment]
Go for it!

**Comment by sladwig** [comment]
So about reseting the game: my thoughts are to add a resetGameEvent, which resets the ctx and gamestate, similar to what happens in the [creation of flow](https://github.com/google/boardgame.io/blob/master/src/core/flow.js#L529)?

**Comment by sladwig** [comment]
since we are saving initial state, we could potentially just return that state from the reducer or am I wrong? not sure (yet) how to access it though... will dig deeper in the next couple of days, but am open for suggestions or other ideas.

**Comment by nicolodavis** [comment]
@sladwig Yes, you could just return the initial state that we already save.

**Comment by sladwig** [comment]
will move undo/redo out then, too.

**Comment by nicolodavis** [comment]
If you've got the time, that would be great. Thanks!

**Comment by nicolodavis** [comment]
@sladwig Also take note of some bugs with the current Undo / Redo implementation that might be easy to spot during the migration:

- We try to remove the API's from `ctx` before adding them to `_undo` [here](https://github.com/google/boardgame.io/blob/master/src/core/flow.js#L329). However, I'm not sure why it's not removed [here](https://github.com/google/boardgame.io/blob/master/src/core/flow.js#L534) as well. This will all be much easier to manage when the undo code is in one place in **reducer.js**.

- In a game prototype that I'm writing, I noticed that `ctx.events` is null inside `onPhaseBegin` whenever an event is called inside `onMove` (it works fine when `onMove` is not present!). I thought https://github.com/google/boardgame.io/commit/87e77c169f15553d98e6c83928a6f3914e6359f1 would fix this, but it doesn't look like it has.
